name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    env:
      Solution_Path: FileIndexer/FileIndexer.sln
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.302'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build App
      run: msbuild $env:Solution_Path /p:Configuration=$env:Configuration
      env:
        Configuration: Debug